name: bluefi
description: A Flutter app for configuring IoT devices over Bluetooth.
version: 1.0.0
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.32.8
  get: ^4.6.6
  dio: ^5.7.0
  flutter_lints: ^6.0.0
  permission_handler: ^12.0.1
  flutter_local_notifications: ^19.4.0
  mobile_scanner: ^7.0.1
flutter:
  uses-material-design: true
  fonts:
    - family: GoogleSans
      fonts:
        - asset: fonts/GoogleSans-Regular.ttf